### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by FDiskas**

### CODE REVIEW

**Comment by FDiskas** [comment]
windows 10
node v6.10.0
npm 3.10.10
result of **index.metadata.json**
```
{"__symbolic":"module","version":3,"metadata":{"MdCoreModule":{"__symbolic":"class","decorators":[{"__symbolic":"call","expression":{"__symbolic":"reference","module":"@angular/core","name":"NgModule"},"arguments":[{}]}],"members":{}},"SOME_EXPORT":"Test"},"origins":{"MdCoreModule":".\\core\\core","SOME_EXPORT":".\\core\\a11y\\live-announcer"},"importAs":"@angular/material"}
```

**Comment by devversion** [comment]
Yeah the metadata files are now emitted. This has been fixed. But the path separators are now invalid.

**Comment by FDiskas** [comment]
The compiler is using webpack?

**Comment by FDiskas** [comment]
I'm usually using https://github.com/webpack/loader-utils

**Pull request closed without merging**
